import os
import pandas as pd
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail
from dotenv import load_dotenv
from datetime import datetime

load_dotenv()

SENDGRID_API_KEY = os.getenv("SENDGRID_API_KEY")
RECIPIENTS = os.getenv("RECIPIENTS", "anna@icardio.com")

digest_file = "data/digest_ready.csv"

def main():
    if not SENDGRID_API_KEY:
        raise ValueError("SENDGRID_API_KEY not set in environment variables")

    if not os.path.exists(digest_file):
        print("Digest file not found.")
        return

    df = pd.read_csv(digest_file)

    if df.empty:
        print("No new papers to email.")
        return

    date_str = datetime.today().strftime("%Y-%m-%d")
    html_table = df.to_html(index=False, escape=False)

    content = f"""
    <h3>Echo-Scout Weekly Digest – {date_str}</h3>
    {html_table}
    <p>– Auto-generated by Echo-Scout</p>
    """

    message = Mail(
        from_email="echo-scout@icardio.ai",
        to_emails=RECIPIENTS.split(","),
        subject=f"New Echo-AI Papers – Week of {date_str}",
        html_content=content,
    )

    try:
        sg = SendGridAPIClient(SENDGRID_API_KEY)
        response = sg.send(message)
        print(f"Email sent. Status Code: {response.status_code}")
    except Exception as e:
        print(f"Error sending email: {e}")

if __name__ == "__main__":
    main()
