import os
import pandas as pd
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

def load_digest():
    digest_path = "data/digest_ready.csv"
    if not os.path.exists(digest_path):
        raise FileNotFoundError("digest_ready.csv not found. Run summarization first.")
    return pd.read_csv(digest_path)

def format_html(df):
    html = """
    <html>
      <body style="font-family: 'Segoe UI', sans-serif; background-color: #f4f6f8; padding: 30px;">
        <div style="max-width: 700px; margin: auto; background-color: #ffffff; border-radius: 10px; padding: 25px; box-shadow: 0 4px 10px rgba(0,0,0,0.05);">
          <h2 style="color: #2c3e50; text-align: center;">🫀 Weekly Digest: Echo-AI Research Highlights</h2>
          <p style="text-align: center; color: #555;">Curated summaries from PubMed and arXiv — powered by GPT-4o</p>
          <hr style="border: none; border-top: 1px solid #e0e0e0;">
    """

    for _, row in df.iterrows():
        html += f"""
        <div style="border: 1px solid #e0e0e0; border-radius: 8px; padding: 15px 20px; margin: 20px 0; background-color: #fdfdfd;">
          <h3 style="color: #007BFF; margin-bottom: 5px;">{row['title']}</h3>
          <p style="margin: 10px 0; color: #333;">{row['summary']}</p>
          <p style="font-size: 0.9em; color: #777;">
            <strong>Lead Author:</strong> {row['lead_author']}<br>
            <strong>Email:</strong> {row['author_email']}
          </p>
          <a href="{row['link']}" style="display: inline-block; margin-top: 8px; padding: 8px 12px; background-color: #007BFF; color: white; text-decoration: none; border-radius: 4px;">🔗 Read Full Article</a>
        </div>
        """

    html += """
          <hr style="border: none; border-top: 1px solid #e0e0e0; margin-top: 40px;">
          <p style="font-size: 0.8em; text-align: center; color: #999;">This digest was automatically generated by the Echo-AI Email Agent.</p>
        </div>
      </body>
    </html>
    """
    return html

def send_email(html_content):
    recipients = os.environ.get("RECIPIENTS")
    if not recipients:
        raise ValueError("RECIPIENTS not set in environment variables.")
    
    message = Mail(
        from_email='gilgurari@gmail.com',
        to_emails=[email.strip() for email in recipients.split(',')],
        subject="🫀 Weekly Digest: Echo-AI Research Highlights",
        html_content=html_content
    )
    try:
        sg = SendGridAPIClient(os.environ.get("SENDGRID_API_KEY"))
        response = sg.send(message)
        print(f"Email sent! Status code: {response.status_code}")
    except Exception as e:
        print(f"Failed to send email: {e}")

def main():
    df = load_digest()
    html_content = format_html(df)
    send_email(html_content)

if __name__ == "__main__":
    main()
