name: Weekly Echo-AI Email Agent

on:
  schedule:
    - cron: '0 16 * * MON'  # Every Monday at 16:00 UTC
  workflow_dispatch:        # Allow manual run from GitHub UI

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip list

      - name: Test Biopython import
        run: |
          python -c "from Bio import Entrez; print('Biopython import successful')"

      - name: Run email agent script
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python agent/main.py
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
