name: weekly-digest
on:
  schedule:
    - cron: '0 16 * * MON'   # Every Monday 09:00 PT
  workflow_dispatch:         # Manual trigger
jobs:
  run-agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python agent/main.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          RECIPIENTS: ${{ secrets.RECIPIENTS }}

