name: weekly-digest

on:
  schedule:
    - cron: '0 16 * * MON'   # Every Monday at 16:00 UTC (adjust timezone if needed)
  workflow_dispatch:         # Manual trigger from GitHub UI

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run agent script
      run: python agent/main.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        RECIPIENTS: ${{ secrets.RECIPIENTS }}
